"""Every model must be reachable from ``app.models``.

Observed in production. A chat session died with

    NoReferencedTableError: Foreign key associated with column
    'ai_sessions.action_run_id' could not find table 'action_runs'

because ``ActionRun`` was in neither the top-level imports of
``app.models`` nor ``_EXTERNAL_MODELS``. It was registered only as a side
effect of some other module importing it, so whether a given process
could flush an ``AISession`` depended on which task had run first. The
first AI session after a restart failed; later ones succeeded; a restart
brought it back.

Nothing caught it because the migrations are hand-written rather than
autogenerated from this metadata, so the table existed in the database
while being absent from the model registry.

These tests are deliberately written against the registry as a whole
rather than against ``action_runs``, because the next omission will be a
different table.
"""

from __future__ import annotations

import pytest
from sqlalchemy.exc import NoReferencedTableError

from app.models import import_all_models
from app.models.base import Base


@pytest.fixture(scope="module", autouse=True)
def _registered() -> None:
    import_all_models()


class TestEveryForeignKeyResolves:
    def test_all_foreign_keys_find_their_table(self) -> None:
        """The check that would have caught the original bug.

        A foreign key whose target table is not in the metadata raises the
        moment SQLAlchemy tries to flush the owning model — in production,
        not here, unless this test exists.
        """
        unresolved: list[str] = []
        for table in Base.metadata.tables.values():
            for fk in table.foreign_keys:
                try:
                    fk.column
                except NoReferencedTableError:
                    unresolved.append(f"{table.name}.{fk.parent.name} -> {fk._colspec}")
        assert not unresolved, (
            "foreign keys point at tables missing from Base.metadata; the owning "
            f"models cannot be flushed: {unresolved}"
        )

    def test_the_regression_case_specifically(self) -> None:
        """Named so a failure here reads as "the old bug is back" rather
        than sending someone through the whole registry."""
        assert "action_runs" in Base.metadata.tables
        assert "ai_sessions" in Base.metadata.tables


class TestTheRegistryIsComplete:
    def test_import_all_models_registers_action_runs(self) -> None:
        """``import_all_models`` is what Alembic and the Celery worker rely
        on to mean "everything". It did not include action_runs, and said
        nothing about it."""
        assert "action_runs" in Base.metadata.tables

    def test_the_worker_registers_models_before_running_tasks(self) -> None:
        """Otherwise the metadata a task sees depends on which task ran
        first, which is how the original bug was intermittent."""
        import inspect

        import app.tasks as tasks

        source = inspect.getsource(tasks)
        assert "worker_process_init" in source
        assert "import_all_models" in source
