import pytest
from pydantic import ValidationError

from app.cron.validators import validate_cron_expression
from app.cron.schemas import CronJobCreate
from app.cron.diff import diff_cron_jobs
from app.cron.collector import _parse_crontab


# ---------------------------------------------------------------------------
# Validator tests (pure function, no DB)
# ---------------------------------------------------------------------------


class TestCronValidator:
    def test_basic_cron_valid(self):
        result = validate_cron_expression("0 2 * * *")
        assert result == ("0", "2", "*", "*", "*")

    def test_step_notation_valid(self):
        result = validate_cron_expression("*/5 * * * *")
        assert result == ("*/5", "*", "*", "*", "*")

    def test_list_notation_valid(self):
        result = validate_cron_expression("0 0 1,15 * *")
        assert result == ("0", "0", "1,15", "*", "*")

    def test_range_notation_valid(self):
        result = validate_cron_expression("0 9-17 * * 1-5")
        assert result == ("0", "9-17", "*", "*", "1-5")

    def test_too_many_fields_rejected(self):
        with pytest.raises(ValueError, match="exactly 5 fields"):
            validate_cron_expression("0 * * * * *")

    def test_too_few_fields_rejected(self):
        with pytest.raises(ValueError, match="exactly 5 fields"):
            validate_cron_expression("* * * *")

    def test_at_special_rejected(self):
        with pytest.raises(ValueError, match="Special schedules"):
            validate_cron_expression("@daily")

    def test_minute_out_of_range(self):
        with pytest.raises(ValueError, match="Invalid minute"):
            validate_cron_expression("60 * * * *")

    def test_hour_out_of_range(self):
        with pytest.raises(ValueError, match="Invalid hour"):
            validate_cron_expression("* 25 * * *")


# ---------------------------------------------------------------------------
# Schema tests (Pydantic validation, no DB)
# ---------------------------------------------------------------------------


class TestCronSchemas:
    def test_invalid_slug_rejected(self):
        with pytest.raises(ValidationError, match="Invalid cron job name"):
            CronJobCreate(
                name="my backup",
                schedule="0 2 * * *",
                command="/usr/bin/backup",
            )

    def test_valid_slug_accepted(self):
        job = CronJobCreate(
            name="daily-backup",
            schedule="0 2 * * *",
            command="/usr/bin/backup",
        )
        assert job.name == "daily-backup"

    def test_invalid_schedule_rejected(self):
        with pytest.raises(ValidationError, match="Special schedules"):
            CronJobCreate(
                name="hourly-task",
                schedule="@hourly",
                command="/usr/bin/task",
            )

    def test_empty_command_rejected(self):
        with pytest.raises(ValidationError, match="command must not be empty"):
            CronJobCreate(
                name="no-cmd",
                schedule="* * * * *",
                command="   ",
            )

    def test_defaults_applied(self):
        job = CronJobCreate(
            name="test-job",
            schedule="0 * * * *",
            command="/bin/true",
        )
        assert job.user == "root"
        assert job.state == "present"
        assert job.priority == 0
        assert job.environment == {}


# ---------------------------------------------------------------------------
# Collector parser tests (no SSH, test _parse_crontab directly)
# ---------------------------------------------------------------------------


class TestCronCollector:
    def test_ansible_marker_parsing(self):
        crontab = (
            "# DO NOT EDIT THIS FILE - edit the master and reinstall.\n"
            "#Ansible: daily-backup\n"
            "0 2 * * * /usr/local/bin/backup.sh\n"
            "#Ansible: log-rotate\n"
            "0 0 * * 0 /usr/sbin/logrotate /etc/logrotate.conf\n"
        )
        entries = _parse_crontab(crontab, "root")
        assert len(entries) == 2
        assert entries[0]["name"] == "daily-backup"
        assert entries[0]["schedule"] == "0 2 * * *"
        assert entries[0]["command"] == "/usr/local/bin/backup.sh"
        assert entries[0]["user"] == "root"
        assert entries[1]["name"] == "log-rotate"
        assert entries[1]["schedule"] == "0 0 * * 0"

    def test_non_managed_entries_skipped(self):
        crontab = (
            "# crontab for deploy\n"
            "*/10 * * * * /usr/bin/check-health\n"
            "0 3 * * * /usr/bin/manual-job\n"
            "#Ansible: managed-task\n"
            "30 4 * * * /opt/scripts/run.sh\n"
        )
        entries = _parse_crontab(crontab, "deploy")
        assert len(entries) == 1
        assert entries[0]["name"] == "managed-task"
        assert entries[0]["user"] == "deploy"
        assert entries[0]["schedule"] == "30 4 * * *"
        assert entries[0]["command"] == "/opt/scripts/run.sh"

    def test_empty_crontab_returns_empty(self):
        entries = _parse_crontab("", "root")
        assert entries == []

    def test_marker_without_following_line_skipped(self):
        crontab = "#Ansible: orphan-marker\n"
        entries = _parse_crontab(crontab, "root")
        assert entries == []


# ---------------------------------------------------------------------------
# Diff engine tests (pure function, no DB)
# ---------------------------------------------------------------------------


class TestCronDiff:
    def test_job_to_add(self):
        desired = [{"name": "backup", "user": "root", "schedule": "0 2 * * *", "command": "/bin/backup"}]
        actual = []
        result = diff_cron_jobs(desired, actual)
        assert "backup|root" in result.jobs_to_add
        assert not result.jobs_to_remove
        assert not result.jobs_in_sync

    def test_job_to_remove(self):
        desired = []
        actual = [{"name": "old-job", "user": "root", "schedule": "0 0 * * *", "command": "/bin/old"}]
        result = diff_cron_jobs(desired, actual)
        assert "old-job|root" in result.jobs_to_remove
        assert not result.jobs_to_add

    def test_job_in_sync(self):
        entry = {"name": "sync-job", "user": "root", "schedule": "0 3 * * *", "command": "/bin/sync"}
        result = diff_cron_jobs([entry], [entry])
        assert "sync-job|root" in result.jobs_in_sync
        assert not result.jobs_to_add
        assert not result.jobs_to_update

    def test_job_to_update_schedule(self):
        desired = {"name": "rotate", "user": "root", "schedule": "0 4 * * *", "command": "/bin/rotate"}
        actual = {"name": "rotate", "user": "root", "schedule": "0 2 * * *", "command": "/bin/rotate"}
        result = diff_cron_jobs([desired], [actual])
        assert "rotate|root" in result.jobs_to_update
        assert not result.jobs_in_sync

    def test_job_to_update_command(self):
        desired = {"name": "task", "user": "root", "schedule": "0 0 * * *", "command": "/bin/new-task"}
        actual = {"name": "task", "user": "root", "schedule": "0 0 * * *", "command": "/bin/old-task"}
        result = diff_cron_jobs([desired], [actual])
        assert "task|root" in result.jobs_to_update

    def test_composite_key(self):
        """Same name, different user = two separate jobs, not merged."""
        desired = [
            {"name": "cleanup", "user": "root", "schedule": "0 1 * * *", "command": "/bin/cleanup"},
            {"name": "cleanup", "user": "deploy", "schedule": "0 2 * * *", "command": "/bin/cleanup"},
        ]
        actual = []
        result = diff_cron_jobs(desired, actual)
        assert "cleanup|root" in result.jobs_to_add
        assert "cleanup|deploy" in result.jobs_to_add
        assert len(result.jobs_to_add) == 2


# ---------------------------------------------------------------------------
# API tests (require DB + superuser_client)
# ---------------------------------------------------------------------------


class TestCronAPI:
    @pytest.mark.asyncio
    async def test_create_group_cron_job(self, superuser_client, db):
        from tests.conftest import create_group

        group = await create_group(db)
        await db.commit()
        resp = await superuser_client.post(
            f"/api/groups/{group.id}/cron-jobs",
            json={
                "name": "daily-backup",
                "schedule": "0 2 * * *",
                "command": "/usr/bin/backup",
            },
        )
        assert resp.status_code == 201
        data = resp.json()
        assert data["name"] == "daily-backup"
        assert data["group_id"] == group.id
        assert data["user"] == "root"
        assert data["state"] == "present"

    @pytest.mark.asyncio
    async def test_invalid_schedule_rejected_by_api(self, superuser_client, db):
        from tests.conftest import create_group

        group = await create_group(db)
        await db.commit()
        resp = await superuser_client.post(
            f"/api/groups/{group.id}/cron-jobs",
            json={
                "name": "bad-schedule",
                "schedule": "@daily",
                "command": "/bin/true",
            },
        )
        assert resp.status_code == 422

    @pytest.mark.asyncio
    async def test_list_group_cron_jobs(self, superuser_client, db):
        from tests.conftest import create_group

        group = await create_group(db)
        await db.commit()
        await superuser_client.post(
            f"/api/groups/{group.id}/cron-jobs",
            json={"name": "job-a", "schedule": "0 1 * * *", "command": "/bin/a"},
        )
        await superuser_client.post(
            f"/api/groups/{group.id}/cron-jobs",
            json={"name": "job-b", "schedule": "0 2 * * *", "command": "/bin/b"},
        )
        resp = await superuser_client.get(f"/api/groups/{group.id}/cron-jobs")
        assert resp.status_code == 200
        names = [j["name"] for j in resp.json()]
        assert "job-a" in names
        assert "job-b" in names

    @pytest.mark.asyncio
    async def test_effective_cron_merge(self, superuser_client, db):
        from tests.conftest import create_group, create_host, create_ssh_key

        group = await create_group(db)
        ssh_key = await create_ssh_key(db)
        host = await create_host(db, ssh_key_id=ssh_key.id, group_ids=[group.id])
        await db.commit()

        await superuser_client.post(
            f"/api/groups/{group.id}/cron-jobs",
            json={
                "name": "deploy-job",
                "schedule": "0 3 * * *",
                "command": "/bin/deploy-group",
            },
        )
        await superuser_client.post(
            f"/api/hosts/{host.id}/cron-jobs",
            json={
                "name": "deploy-job",
                "schedule": "0 4 * * *",
                "command": "/bin/deploy-host",
            },
        )

        resp = await superuser_client.get(f"/api/hosts/{host.id}/effective-cron-jobs")
        assert resp.status_code == 200
        data = resp.json()
        deploy = [j for j in data if j["name"] == "deploy-job"]
        assert len(deploy) == 1
        assert deploy[0]["source"] == "host"
        assert deploy[0]["command"] == "/bin/deploy-host"
        assert deploy[0]["schedule"] == "0 4 * * *"
