"""add collected_state and barricade_source_ip

Revision ID: 10dc6150ee58
Revises: 855128c66d0c
Create Date: 2026-03-24 22:54:27.125247

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "10dc6150ee58"
down_revision: str | Sequence[str] | None = "855128c66d0c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "host_module_status",
        sa.Column("collected_state", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "host_module_status", sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("hosts", sa.Column("barricade_source_ip", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hosts", "barricade_source_ip")
    op.drop_column("host_module_status", "collected_at")
    op.drop_column("host_module_status", "collected_state")
    # ### end Alembic commands ###
