"""add hold to package_rules

Revision ID: 621b11ca3608
Revises: d87b771ba89d
Create Date: 2026-03-20 00:31:04.731841

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "621b11ca3608"
down_revision: str | Sequence[str] | None = "d87b771ba89d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "package_rules",
        sa.Column("hold", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("package_rules", "hold")
    # ### end Alembic commands ###
