"""add vm_mappings table

Revision ID: 6738a0f7215e
Revises: a847f54c355b
Create Date: 2026-03-26 21:38:46.583992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6738a0f7215e'
down_revision: Union[str, Sequence[str], None] = 'a847f54c355b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vm_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('proxmox_node_id', sa.Integer(), nullable=False),
    sa.Column('pve_node_name', sa.String(length=100), nullable=False),
    sa.Column('vmid', sa.Integer(), nullable=False),
    sa.Column('vm_name', sa.String(length=200), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], name=op.f('fk_vm_mappings_host_id_hosts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proxmox_node_id'], ['proxmox_nodes.id'], name=op.f('fk_vm_mappings_proxmox_node_id_proxmox_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vm_mappings'))
    )
    op.create_index(op.f('ix_vm_mappings_host_id'), 'vm_mappings', ['host_id'], unique=True)
    op.create_index(op.f('ix_vm_mappings_proxmox_node_id'), 'vm_mappings', ['proxmox_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_mappings_proxmox_node_id'), table_name='vm_mappings')
    op.drop_index(op.f('ix_vm_mappings_host_id'), table_name='vm_mappings')
    op.drop_table('vm_mappings')
    # ### end Alembic commands ###
