"""add ssh_user to ssh_keys

Revision ID: 855128c66d0c
Revises: 621b11ca3608
Create Date: 2026-03-24 19:38:07.520675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '855128c66d0c'
down_revision: Union[str, Sequence[str], None] = '621b11ca3608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ssh_keys', sa.Column('ssh_user', sa.String(length=32), nullable=False, server_default='root'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ssh_keys', 'ssh_user')
    # ### end Alembic commands ###
