"""add proxmox_nodes and workflow tables

Revision ID: a847f54c355b
Revises: a1b2c3d4e5f6
Create Date: 2026-03-26 21:26:37.150496

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a847f54c355b"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proxmox_nodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("api_url", sa.String(length=500), nullable=False),
        sa.Column("token_id", sa.String(length=200), nullable=False),
        sa.Column("encrypted_token_secret", sa.LargeBinary(), nullable=False),
        sa.Column("verify_ssl", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proxmox_nodes")),
    )
    op.create_index(op.f("ix_proxmox_nodes_name"), "proxmox_nodes", ["name"], unique=True)
    op.create_table(
        "update_workflows",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("batch_size", sa.Integer(), nullable=False),
        sa.Column("schedule_cron", sa.String(length=100), nullable=True),
        sa.Column("pre_update_snapshot", sa.Boolean(), nullable=False),
        sa.Column("auto_rollback", sa.Boolean(), nullable=False),
        sa.Column("verification_prompt", sa.Text(), nullable=True),
        sa.Column("auto_reboot", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["host_groups.id"],
            name=op.f("fk_update_workflows_group_id_host_groups"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_update_workflows")),
        sa.UniqueConstraint("group_id", name=op.f("uq_update_workflows_group_id")),
    )
    op.create_table(
        "workflow_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "completed", "failed", "partial", name="workflowrunstatus"
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triggered_by", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["triggered_by"],
            ["users.id"],
            name=op.f("fk_workflow_runs_triggered_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["update_workflows.id"],
            name=op.f("fk_workflow_runs_workflow_id_update_workflows"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_runs")),
    )
    op.create_table(
        "workflow_host_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column(
            "step",
            sa.Enum(
                "preflight",
                "snapshot",
                "update",
                "reboot",
                "verify",
                "cleanup",
                "rollback",
                name="workflowstep",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "running", "success", "failed", "skipped", name="workflowhoststatus"
            ),
            nullable=False,
        ),
        sa.Column("snapshot_name", sa.String(length=200), nullable=True),
        sa.Column("step_output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["hosts.id"],
            name=op.f("fk_workflow_host_runs_host_id_hosts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["workflow_runs.id"],
            name=op.f("fk_workflow_host_runs_run_id_workflow_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workflow_host_runs")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workflow_host_runs")
    op.drop_table("workflow_runs")
    op.drop_table("update_workflows")
    op.drop_index(op.f("ix_proxmox_nodes_name"), table_name="proxmox_nodes")
    op.drop_table("proxmox_nodes")
    op.execute("DROP TYPE IF EXISTS workflowrunstatus")
    op.execute("DROP TYPE IF EXISTS workflowhoststatus")
    op.execute("DROP TYPE IF EXISTS workflowstep")
    # ### end Alembic commands ###
