"""add ssh_user to hosts

Revision ID: aa2c23fb6625
Revises: 0008
Create Date: 2026-03-19 22:52:06.451065

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa2c23fb6625"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("uq_cron_jobs_group_name_user"),
        table_name="cron_jobs",
        postgresql_where="(group_id IS NOT NULL)",
    )
    op.drop_index(
        op.f("uq_cron_jobs_host_name_user"),
        table_name="cron_jobs",
        postgresql_where="(host_id IS NOT NULL)",
    )
    op.drop_constraint(
        op.f("fk_git_repositories_ssh_key_id_ssh_keys"), "git_repositories", type_="foreignkey"
    )
    op.drop_constraint(op.f("uq_host_groups_name"), "host_groups", type_="unique")
    op.add_column(
        "hosts", sa.Column("ssh_user", sa.String(length=32), server_default="root", nullable=False)
    )
    op.drop_constraint(op.f("uq_hosts_hostname"), "hosts", type_="unique")
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("uq_hosts_hostname"), "hosts", ["hostname"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("hosts", "ssh_user")
    op.create_unique_constraint(
        op.f("uq_host_groups_name"), "host_groups", ["name"], postgresql_nulls_not_distinct=False
    )
    op.create_foreign_key(
        op.f("fk_git_repositories_ssh_key_id_ssh_keys"),
        "git_repositories",
        "ssh_keys",
        ["ssh_key_id"],
        ["id"],
    )
    op.create_index(
        op.f("uq_cron_jobs_host_name_user"),
        "cron_jobs",
        ["host_id", "name", "user"],
        unique=True,
        postgresql_where="(host_id IS NOT NULL)",
    )
    op.create_index(
        op.f("uq_cron_jobs_group_name_user"),
        "cron_jobs",
        ["group_id", "name", "user"],
        unique=True,
        postgresql_where="(group_id IS NOT NULL)",
    )
    # ### end Alembic commands ###
