"""add category to host_groups

Revision ID: d87b771ba89d
Revises: aa2c23fb6625
Create Date: 2026-03-19 23:32:48.289529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd87b771ba89d'
down_revision: Union[str, Sequence[str], None] = 'aa2c23fb6625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('host_groups', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('host_groups', 'category')
    # ### end Alembic commands ###
