import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Sidebar is auto-generated from the `docs/` tree layout.  Every
// subdirectory becomes a category; every `README.md` becomes the
// default page for that category.  Manual overrides can be added
// here later if needed.
const sidebars: SidebarsConfig = {
  defaultSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
