import ipaddress

from app.rules.model import ChainPolicies, FirewallRuleSpec

_COMMENT_PREFIX = "Managed by LabDog"


def _safe_comment(text: str | None) -> str:
    """Build the unified comment string, sanitised for iptables embedding.

    iptables-restore tolerates double-quoted comment values up to 256 bytes;
    embedded double quotes and newlines would break the line. We strip those
    and cap length to leave headroom under the kernel limit.
    """
    base = _COMMENT_PREFIX
    if text:
        cleaned = text.replace('"', "'").replace("\n", " ").replace("\t", " ").strip()
        if cleaned:
            base = f"{_COMMENT_PREFIX}: {cleaned}"
    return base[:200]


def _comment_match(text: str | None) -> str:
    return f'-m comment --comment "{_safe_comment(text)}"'


def _rule_to_iptables(rule: FirewallRuleSpec, chain: str, ipv6: bool = False) -> str:
    """Convert rule to iptables-save format line."""
    cmd = "-A " + chain
    if rule.source_cidr:
        cmd += f" -s {rule.source_cidr}"
    if rule.destination_cidr:
        cmd += f" -d {rule.destination_cidr}"
    if rule.protocol not in (None, "any"):
        cmd += f" -p {rule.protocol}"
        if rule.port_start is not None:
            if rule.port_end and rule.port_end != rule.port_start:
                cmd += f" --dport {rule.port_start}:{rule.port_end}"
            else:
                cmd += f" --dport {rule.port_start}"
    action_map = {"allow": "ACCEPT", "deny": "DROP", "reject": "REJECT"}
    cmd += f" {_comment_match(rule.comment)}"
    cmd += f" -j {action_map.get(rule.action, 'DROP')}"
    return cmd


def render_iptables_rules(
    rules: list[FirewallRuleSpec],
    policies: ChainPolicies | None = None,
) -> tuple[str, str]:
    """
    Returns (ipv4_content, ipv6_content) in iptables-restore format.
    """
    if policies is None:
        policies = ChainPolicies()

    def is_ipv6_rule(rule: FirewallRuleSpec) -> bool:
        if rule.source_cidr:
            try:
                return ipaddress.ip_network(rule.source_cidr, strict=False).version == 6
            except ValueError:
                pass
        return False

    ipv4_rules = [r for r in rules if not is_ipv6_rule(r)]
    ipv6_rules = [r for r in rules if is_ipv6_rule(r)]

    def make_rules_file(rule_list: list[FirewallRuleSpec], ipv6: bool = False) -> str:
        lines = [
            "# Rules automatically generated by LabDog",
            "*filter",
            ":LABDOG-INPUT - [0:0]",
            ":LABDOG-OUTPUT - [0:0]",
            # Flush our chains so this is idempotent
            "-F LABDOG-INPUT",
            "-F LABDOG-OUTPUT",
            # Infrastructure rules in our input chain
            f'-A LABDOG-INPUT -m state --state ESTABLISHED,RELATED {_comment_match("stateful tracking")} -j ACCEPT',
            f'-A LABDOG-INPUT -i lo {_comment_match("loopback")} -j ACCEPT',
        ]
        for rule in rule_list:
            chain = "LABDOG-INPUT" if rule.direction == "input" else "LABDOG-OUTPUT"
            lines.append(_rule_to_iptables(rule, chain, ipv6))
        # Apply chain default policies via final rules
        input_target = "DROP" if policies.input == "drop" else "ACCEPT"
        output_target = "DROP" if policies.output == "drop" else "ACCEPT"
        lines.append(f'-A LABDOG-INPUT {_comment_match("default policy")} -j {input_target}')
        lines.append(f'-A LABDOG-OUTPUT {_comment_match("default policy")} -j {output_target}')
        lines += ["COMMIT", ""]
        return "\n".join(lines)

    return make_rules_file(ipv4_rules), make_rules_file(ipv6_rules, ipv6=True)
