import ipaddress
from app.rules.model import FirewallRuleSpec


def _rule_to_iptables(rule: FirewallRuleSpec, chain: str, ipv6: bool = False) -> str:
    """Convert rule to iptables-save format line."""
    cmd = "-A " + chain
    if rule.source_cidr:
        cmd += f" -s {rule.source_cidr}"
    if rule.destination_cidr:
        cmd += f" -d {rule.destination_cidr}"
    if rule.protocol not in (None, "any"):
        cmd += f" -p {rule.protocol}"
        if rule.port_start is not None:
            if rule.port_end and rule.port_end != rule.port_start:
                cmd += f" --dport {rule.port_start}:{rule.port_end}"
            else:
                cmd += f" --dport {rule.port_start}"
    action_map = {"allow": "ACCEPT", "deny": "DROP", "reject": "REJECT"}
    cmd += f" -j {action_map.get(rule.action, 'DROP')}"
    return cmd


def render_ufw_rules(rules: list[FirewallRuleSpec]) -> tuple[str, str]:
    """
    Returns (user.rules content, user6.rules content) for UFW.
    Writes directly to /etc/ufw/user.rules format.
    """

    def is_ipv6_rule(rule: FirewallRuleSpec) -> bool:
        if rule.source_cidr:
            try:
                return ipaddress.ip_network(rule.source_cidr, strict=False).version == 6
            except ValueError:
                pass
        return False

    ipv4_rules = [r for r in rules if not is_ipv6_rule(r)]
    ipv6_rules = [r for r in rules if is_ipv6_rule(r)]

    def make_rules_file(rule_list: list[FirewallRuleSpec], ipv6: bool = False) -> str:
        lines = [
            "# Rules automatically generated by Barricade",
            "*filter",
            ":ufw-user-input - [0:0]",
            ":ufw-user-output - [0:0]",
            ":ufw-user-forward - [0:0]",
        ]
        for rule in rule_list:
            chain = "ufw-user-input" if rule.direction == "input" else "ufw-user-output"
            lines.append(_rule_to_iptables(rule, chain, ipv6))
        lines += ["COMMIT", ""]
        return "\n".join(lines)

    return make_rules_file(ipv4_rules), make_rules_file(ipv6_rules, ipv6=True)
